model_path: /opt/models/r1041_e82_400bps_sup_v420/
samplesheet: batch1.csv
sourceDir: /hpcfs/users/a1767591/Wagyu_SV/batch1_results
reference: /hpcfs/users/a1767591/Wagyu_SV/ARS-UCD_BLRC/ARS_UCD_v2.0.fa
reference_idx: /hpcfs/users/a1767591/Wagyu_SV/ARS-UCD_BLRC/ARS_UCD_v2.0.fa.fai
minimap_index: /hpcfs/users/a1767591/Wagyu_SV/ARS-UCD_BLRC/ARS_UCD_v2.0.mmi
skip_snps: false
methylation: false
only_svs: false
temp_dir: /hpcfs/users/a1767591/Wagyu_SV/dysgu_temp